"""empty message

Revision ID: 0d0d5da33081
Revises: 2f3c1625844c
Create Date: 2022-07-13 21:24:04.881083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0d5da33081'
down_revision = '2f3c1625844c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pistas', sa.Column('city', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pistas', 'city')
    # ### end Alembic commands ###
