"""empty message

Revision ID: 14a8410d2c2a
Revises: 89b253ea60c1
Create Date: 2022-06-05 15:21:02.030623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a8410d2c2a'
down_revision = '89b253ea60c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('city', sa.String(length=80), nullable=False))
    op.add_column('pistas', sa.Column('events_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pistas', 'events', ['events_id'], ['id'])
    op.add_column('sports', sa.Column('events_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sports', 'events', ['events_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sports', type_='foreignkey')
    op.drop_column('sports', 'events_id')
    op.drop_constraint(None, 'pistas', type_='foreignkey')
    op.drop_column('pistas', 'events_id')
    op.drop_column('events', 'city')
    # ### end Alembic commands ###
