"""empty message

Revision ID: 1ed91fc945b6
Revises: 13dd3914e8d9
Create Date: 2022-05-23 13:56:17.379233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed91fc945b6'
down_revision = '13dd3914e8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('apellidos', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('birth', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('genero', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'genero')
    op.drop_column('user', 'birth')
    op.drop_column('user', 'apellidos')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
