"""empty message

Revision ID: 1f384e81f0ff
Revises: 12727915b2d8
Create Date: 2022-06-23 09:22:39.337354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f384e81f0ff'
down_revision = '12727915b2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
