"""empty message

<<<<<<< HEAD:migrations/versions/aa405c73eef9_.py
Revision ID: aa405c73eef9
Revises: 
Create Date: 2022-05-24 19:17:52.203502
=======
Revision ID: 28f0be3b10a4
Revises: 
Create Date: 2022-05-24 19:08:15.340144
>>>>>>> f6b9375b756597efd271549c33f38c5d156efc97:migrations/versions/28f0be3b10a4_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/aa405c73eef9_.py
revision = 'aa405c73eef9'
=======
revision = '28f0be3b10a4'
>>>>>>> f6b9375b756597efd271549c33f38c5d156efc97:migrations/versions/28f0be3b10a4_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
<<<<<<< HEAD:migrations/versions/aa405c73eef9_.py
    sa.Column('surname', sa.String(length=80), nullable=True),
    sa.Column('birth', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('sports', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
=======
    sa.Column('birth', sa.String(length=80), nullable=True),
>>>>>>> f6b9375b756597efd271549c33f38c5d156efc97:migrations/versions/28f0be3b10a4_.py
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
