"""empty message

Revision ID: 41dec67fe03a
Revises: 4cabc08cc9df
Create Date: 2022-06-10 15:52:25.928650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41dec67fe03a'
down_revision = '4cabc08cc9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image_url')
    # ### end Alembic commands ###
