"""empty message

Revision ID: f20b8198c2c5
Revises: 93a9cb718b6a
Create Date: 2022-06-09 20:19:54.841791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20b8198c2c5'
down_revision = '93a9cb718b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###
